apiVersion: apps/v1
kind: Deployment
metadata:
  name: postgresql
  namespace: swap-dev
  labels:
    app: postgresql
spec:
  replicas: 1
  selector:
    matchLabels:
      app: postgresql
  template:
    metadata:
      labels:
        app: postgresql
        node: backend
    spec:
      containers:
        - name: postgresql
          image: postgres:14.1-alpine
          ports:
            - containerPort: 5432
          env:
            - name: POSTGRES_DB
              value: swap-dev
            - name: POSTGRES_USER
              value: user_swap
            - name: PGDATA
              value: /var/lib/postgresql/data/swap_token
            - name: POSTGRES_PASSWORD
              value: b147420fcd0adfadsfadsfkdkadi9f71649f0d98c9e9c8165
          volumeMounts:
            - mountPath: '/var/lib/postgresql/data'
              name: 'postgresql-data-storage'
          # resources:
          #   requests:
          #     cpu: '500m'
          #     memory: '500Mi'
          #   limits:
          #     cpu: '1000m'
          #     memory: '1000Mi'
      volumes:
        - name: postgresql-data-storage
          persistentVolumeClaim:
            claimName: postgresql-data
