apiVersion: v1
kind: Secret
metadata:
  name: influxdb
  namespace: backend
type: Opaque
data:
  # echo -n influx-admin | base64 | pbcopy
  admin-user: aW5mbHV4LWFkbWlu
  # echo -n E6zJRThw | base64 | pbcopy
  admin-password: RTZ6SlJUaHc=
  # echo -n yokef | base64 | pbcopy
  user: eW9rZWY=
  # echo -n zR7Up82h | base64 | pbcopy
  user-password: elI3VXA4Mmg=
