apiVersion: v1
kind: Secret
metadata:
  name: rabbitmq
  namespace: backend
  labels:
    app.kubernetes.io/name: rabbitmq
    app.kubernetes.io/instance: rabbitmq
    app.kubernetes.io/managed-by: Helm
  annotations:
    meta.helm.sh/release-name: rabbitmq
    meta.helm.sh/release-namespace: backend
type: Opaque
data:
  rabbitmq-password: Rmw0ZndETERQUQo=
