apiVersion: apps/v1
kind: Deployment
metadata:
  name: agenda
  namespace: swap-prd
  labels:
    app: agenda
spec:
  replicas: 1
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 0
  selector:
    matchLabels:
      app: agenda
  template:
    metadata:
      labels:
        app: agenda
        node: backend
      # annotations:
      #   vault.security.banzaicloud.io/vault-addr: "http://vault.vault.svc.cluster.local:8200"
      #   vault.security.banzaicloud.io/vault-role: "default"
    spec:
      containers:
        - name: agenda
          imagePullPolicy: Always
          image: asia-southeast1-docker.pkg.dev/novaland-337909/novaland-registry/backend-swap-api:20220327-150352-20220328
          command: ["/bin/sh","-c"]
          args: ["NODE_ENV=production yarn ts src/agenda.ts"]
          resources:
            limits:
              memory: "512Mi"
              cpu: "250m"
            requests:
              memory: "512Mi"
              cpu: "250m"
          # env:
          #   - name: DATABASE_URL
          #     value: vault:secret/backend#DATABASE_URL
          #   - name: ETHEREUM_PROVIDER
          #     value: vault:secret/backend#ETHEREUM_PROVIDER
          #   - name: BINANCE_API_KEY
          #     value: vault:secret/backend#BINANCE_API_KEY
          #   - name: BINANCE_SECRET_KEY
          #     value: vault:secret/backend#BINANCE_SECRET_KEY
          #   - name: VNBANK_TOKEN
          #     value: vault:secret/backend#VNBANK_TOKEN
          #   - name: FIREBASE_PUSH_KEY
          #     value: vault:secret/backend#FIREBASE_PUSH_KEY
