apiVersion: apps/v1
kind: Deployment
metadata:
  name: auth-service
  namespace: swap-prd
  labels:
    app: auth-service
spec:
  replicas: 1
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 0
  selector:
    matchLabels:
      app: auth-service
  template:
    metadata:
      labels:
        app: auth-service
        node: auth-service
      # annotations:
      #   vault.security.banzaicloud.io/vault-addr: "http://vault.vault.svc.cluster.local:8200"
      #   vault.security.banzaicloud.io/vault-role: "default"
    spec:
      imagePullSecrets:
        - name: golduck-registry
      containers:
        - name: auth-service
          image: asia-southeast1-docker.pkg.dev/novaland-337909/novaland-registry/backend-swap-api:20220330-170612-20220331
          command: ["/bin/sh","-c"]
          args: ["NODE_ENV=production node dist/services/auth-services"]
          # env:
          #   - name: DATABASE_URL
          #     value: vault:secret/backend#DATABASE_URL
          #   - name: JWT_PUBLIC_KEY
          #     value: vault:secret/backend#JWT_PUBLIC_KEY
          #   - name: JWT_SECRET_KEY
          #     value: vault:secret/backend#JWT_SECRET_KEY
          resources:
            requests:
              memory: "500Mi"
              cpu: "500"
            limits:
              memory: "1Gi"
              cpu: "1"
          ports:
            - name: auth-service
              containerPort: 4000

---
apiVersion: v1
kind: Service
metadata:
  name: auth-service
  namespace: swap-prd
  labels:
    app: auth-service
spec:
  type: ClusterIP
  ports:
    - port: 4000
  selector:
    app: auth-service
