apiVersion: getambassador.io/v2
kind: Mapping
metadata:
  name: hasura
  namespace: swap-prd
spec:
  prefix: /hasura/
  # host: "^(api.voption.org)$"
  # host_regex: true
  service: hasura
  use_websocket: true
  timeout_ms: 25000
  connect_timeout_ms: 5000
