apiVersion: getambassador.io/v2
kind: Mapping
metadata:
  name: hasura
  namespace: swap-dev
spec:
  prefix: /hasura/
  host: "^(begacy-dev.vncht.com|begacy-dev.slotkoin.com)$"
  host_regex: true
  service: hasura
  use_websocket: true
  timeout_ms: 25000
  connect_timeout_ms: 5000
