export * from './AuthPayload'
export * from './Mutation'
export * from './Query'
export * from './User'
export * from './Currency'
export * from './Subscription'
export * from './Wallet'
export * from './Orders'
export * from './Convertion'
export * from './Transaction'
export * from './Period'
export * from './CandleStick'
export * from './ExchangePair'
export * from './Round'
export * from './DashBoardStatsPayload'
export * from './Ref'
export * from './CoinheID'
export * from './TwoFA'
export * from './InternalTransaction'
export * from './PromotionCode'
export * from './LeaderBoard'
export * from './CopyTrade'
export * from './TradeBattle'
export * from './ExpertRegister'
// export * from './ServiceSubscription'
// export * from './Plan'
export * from './Notification'
// export * from './Ring'

export * from './Insurance'

// Scalar Type
export * from './Upload'

export * from './BotSignal'

export * from './BotAirdrop'

// ADMIN TYPE
export * from './admin/TokenLogin'
export * from './admin/auth'
export * from './admin/convertion'
export * from './admin/exchange'
export * from './admin/transaction'
export * from './admin/user'
export * from './admin/AdminUser'
export * from './admin/Platform'
// export * from './admin/ticket'
export * from './admin/wallet'
// export * from './admin/statistic'
export * from './admin/expert'
export * from './admin/notification'
export * from './admin/Blackbox'
export * from './admin/RoundTracking'
export * from './admin/Currency'
export * from './admin/DashboardV2'
// export * from './admin/AdminOrder'
export * from './admin/Round'
export * from './admin/Ref'
export * from './Country'
export * from './admin/FakeData'
