apiVersion: apps/v1
kind: Deployment
metadata:
  name: redis
  namespace: swap-dev
  labels:
    app: redis
spec:
  replicas: 1
  selector:
    matchLabels:
      app: redis
  template:
    metadata:
      labels:
        app: redis
        node: backend
    spec:
      containers:
        - image: redis:alpine
          name: redis
          ports:
            - containerPort: 6379
              name: redis
          volumeMounts:
            - mountPath: /var/lib/redis
              name: redis-data-storage
          livenessProbe:
            exec:
              command:
                - redis-cli
                - ping
            initialDelaySeconds: 30
            timeoutSeconds: 5
          readinessProbe:
            exec:
              command:
                - redis-cli
                - ping
            initialDelaySeconds: 5
            timeoutSeconds: 1
          # resources:
          #   requests:
          #     cpu: '500m'
          #     memory: '500Mi'
          #   limits:
          #     cpu: '1000m'
          #     memory: '1000Mi'
      volumes:
        - name: redis-data-storage
          persistentVolumeClaim:
            claimName: redis-data
