apiVersion: apps/v1
kind: Deployment
metadata:
  name: agenda
  namespace: swap-dev
  labels:
    app: agenda
spec:
  replicas: 1
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 0
  selector:
    matchLabels:
      app: agenda
  template:
    metadata:
      labels:
        app: agenda
        node: backend
      # annotations:
      #   vault.security.banzaicloud.io/vault-addr: "http://vault.vault.svc.cluster.local:8200"
      #   vault.security.banzaicloud.io/vault-role: "default"
    spec:
      # imagePullSecrets:
      #   - name: golduck-registry
      containers:
        - name: agenda
          imagePullPolicy: Always
          # image: asia.gcr.io/base-operation-service/coinhe-dev/backend-swap-api:20220326-173206-20220327
          image: asia-southeast1-docker.pkg.dev/novaland-337909/novaland-registry/backend-swap-api-dev:20220327-105331-20220328
          command: ["/bin/sh","-c"]
          args: ["NODE_ENV=production yarn ts src/agenda.ts"]
          env:
            - name: GET_HOSTS_FROM
              value: dns
            # - name: DATABASE_URL
            #   value: vault:secret/backend#DATABASE_URL
