---
apiVersion: getambassador.io/v2
kind: Host
metadata:
  name: dev-api.voption.org
spec:
  hostname: dev-api.voption.org
  acmeProvider:
    authority: https://acme-v02.api.letsencrypt.org/directory # Optional: The CA you want to get your certificate from. Defaults to Let's Encrypt
    email: admin@domain.com
