apiVersion: v1
kind: Service
metadata:
  name: redis
  namespace: backend
  labels:
    app: redis
spec:
  type: NodePort
  ports:
    - name: redis
      port: 6379
      targetPort: redis
  selector:
    app: redis
